name: shefa
recipe: wordpress
proxy:
  appserver:
    - shefa.local
config:
  php: '8.0'
  via: apache
  webroot: .
  xdebug: true
services:
  database:
    portforward: true
    type: mysql
    creds:
      user: shefadb
      password: shefadb
      database: shefadb
  pma:
    type: phpmyadmin
    hosts: database